language: java
sudo: required

jdk:
  - oraclejdk8

services:
  - postgresql

before_install:
  - sudo apt-get update

  # Setup to be able to run Chrome in Travis
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y libappindicator1 fonts-liberation

  # Setup Google Chrome
  - export WEBDRIVER_PATH=/usr/bin/google-chrome
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

  # Setup Google Chrome Webdriver
  - mkdir bin
  - wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -O bin/chromedriver.zip
  - unzip -d bin bin/chromedriver.zip

  # Setup Codacy Executable
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - psql -c 'create database family_menu;' -U postgres

script: ./gradlew --info --parallel clean check jacocoTestReport jacocoIntegrationTestCoverageReport

after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml -r build/reports/jacoco/jacocoIntegrationTestCoverageReport/jacocoIntegrationTestCoverageReport.xml
