language: java
sudo: required

jdk:
  - oraclejdk8

services:
  - postgresql

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - psql -c 'create database family_menu;' -U postgres

script: ./gradlew --parallel clean check jacocoTestReport jacocoIntegrationTestCoverageReport

after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml -r build/reports/jacoco/jacocoIntegrationTestCoverageReport/jacocoIntegrationTestCoverageReport.xml
