api.base.path: /api/v1

liquibase.change-log: classpath:/db/changelog/master.xml

spring.datasource:
  url: jdbc:postgresql://localhost:5432/family_menu
  username:
  password:

spring.jpa.hibernate.ddl-auto: validate
